apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nicomuros/final-acsofttek-backend:0.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-database
            - name: DB_USERNAME
              valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: mysql-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-password
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
    selector:
        app: backend
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
    type: LoadBalancer