apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
        name: frontend
        labels:
            app: frontend
    spec:
      containers:
        - name: frontend
          image: nicomuros/final-acsofttek-frontend:0.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: VITE_BACKEND_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: backend-host
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
    selector:
        app: frontend
    ports:
      - protocol: TCP
        port: 80
        targetPort: 5173
    type: LoadBalancer

